@startuml network

!include <office/Servers/application_server>
!include <office/Servers/database_server>
!include <office/Devices/router>
!include <office/Devices/device_laptop>

' Center the text
skinparam defaultFontSize 12

nwdiag {
    network GameMaster {
        address = "10.10.0.0/24"
        scoreboard [address = "10.10.0.1", description = "<$application_server>\nScoreboard"];
        game_service [address = "10.10.0.1", description = "<$application_server>\nGame\nService"];
        
        router [address = "10.10.0.254", description = "<$router>\n Router"];
    }
    network Team1 {
        address = "10.60.1.x/24"
        computer1_1 [address = "10.60.1.2", description = "<$device_laptop>\n    PC 1"];
        computer1_2 [address = "10.60.1.3", description = "<$device_laptop>\n    PC 2"];
        computer1_3 [address = "10.60.1.3", description = "<$device_laptop>\n    PC 3"];
        router [address = "10.60.1.254", description = "<$router>\n router"];
    }
    network Team2 {
        address = "10.60.2.x/24"
        computer2_1 [address = "10.60.2.2", description = "<$device_laptop>\n    PC 1"];
        computer2_2 [address = "10.60.2.3", description = "<$device_laptop>\n    PC 2"];
        computer2_3 [address = "10.60.2.3", description = "<$device_laptop>\n    PC 3"];
        router [address = "10.60.2.254", description = "<$router>\n router"];
    }
    network TeamN {
        address = "10.60.N.x/24"
        computerN_1 [address = "10.60.N.2", description = "<$device_laptop>\n    PC 1"];
        computerN_2 [address = "10.60.N.3", description = "<$device_laptop>\n    PC 2"];
        computerN_3 [address = "10.60.N.3", description = "<$device_laptop>\n    PC 3"];
        router [address = "10.60.N.254", description = "<$router>\n router"];
    }
}

@enduml
