---
- name: "Uninstall default packages"
  become: true
  ansible.builtin.package:
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - podman-docker
      - containerd
      - runc
    state: absent

- name: "Install deps"
  become: true
  ansible.builtin.package:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present

- name: "Add Docker GPG apt Key"
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

# - name: "Get os-release"
#   become: true
#   ansible.builtin.shell: . /etc/os-release && echo "$VERSION_CODENAME"
#   register: os_release
#   changed_when: true
#   args:
#     executable: /bin/bash

- name: Name
  ansible.builtin.debug:
    var: ansible_distribution_release

- name: Add Docker Repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Update apt and install docker-ce
  become: true
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true

- name: Restart docker and enable on boot
  become: true
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: restarted
