---
- name: Generate wireguard private and public keys
  become: true
  ansible.builtin.shell: |
    set -o pipefail
    umask 077
    wg genkey | tee /etc/wireguard/privatekey | wg pubkey > /etc/wireguard/publickey
  args:
    creates: /etc/wireguard/privatekey
    executable: /bin/bash

- name: Store public key in variable
  become: true
  ansible.builtin.slurp:
    src: /etc/wireguard/publickey
  register: server_pk

- name: Wireguard config
  become: true
  ansible.builtin.template:
    src: templates/server.wireguard.conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: "0600"

- name: Program the starting of the network after a set delay
  become: true
  ansible.builtin.cron:
    name: "Start vpn network"
    month: "{{ start_conf.month }}"
    day: "{{ start_conf.day }}"
    hour: "{{ start_conf.hour }}"
    minute: "{{ start_conf.minute + 1 }}" # make sure it starts after the router
    job: "wg-quick up wg0"
    user: root
    state: present
  vars:
    start_conf: "{{ wireguard.router.start }}"
