all:
  hosts:
    router:
      ansible_host: 20.224.110.170 # router public ip (don't remove the comment for run.sh)
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ./keys/router.pem
    server:
      ansible_host: 192.168.1.4 # server private ip (don't remove the comment for run.sh)
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ./keys/server.pem
      ansible_ssh_common_args: '-o ProxyCommand="ssh -i ./keys/router.pem -W %h:%p ubuntu@20.224.110.170"'
  children:
    vulnbox:
      hosts:
        vulnbox1:
          ansible_host: 192.168.2.4 # vulnbox1 (don't remove the comment for run.sh)
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ./keys/vulnbox1.pem
          ansible_ssh_common_args: '-o ProxyCommand="ssh -i ./keys/router.pem -W %h:%p ubuntu@20.224.110.170"'
        vulnbox2:
          ansible_host: 192.168.2.5 # vulnbox2 (don't remove the comment for run.sh)
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ./keys/vulnbox2.pem
          ansible_ssh_common_args: '-o ProxyCommand="ssh -i ./keys/router.pem -W %h:%p ubuntu@20.224.110.170"'
  vars:
    ansible_ssh_timeout: 30
    wireguard:
      network: 10.0.0.0/8
      router:
        private_ip: 192.168.0.4
        port: 51820
        ip: "10.0.0.1"
        subnet: 10.0.0.1/32
        out_interface: eth0
        start:
          year: 2023
          month: 7
          day: 15
          hour: 12
          minute: 10
        open:
          year: 2023
          month: 7
          day: 15
          hour: 12
          minute: 15
      vulnbox:
        port: 51820
        ip_format: 10.60.%d.1
        subnet: 10.60.0.0/16
        team_mask_offset: 8
      player:
        ip_format: 10.80.%d.%d
        subnet: 10.80.0.0/16
        team_mask_offset: 8
      server:
        port: 51820
        ip: 10.10.0.1
        subnet: 10.10.0.0/16
    teams:
      - name: catania
        players: 1
      - name: palermo
        players: 2
    ad:
      timezone: Europe/Rome
      round_time: 60
      default_score: 2500
      flag_lifetime: 5
      vulnbox:
        services_owner: root
        services_path: /root/services/
