---
- name: Common configuration
  hosts: all

  tasks:
    - name: Installs common packages
      ansible.builtin.include_tasks: ./tasks/common.yml

- name: Docker configuration
  hosts:
    - vulnbox
    - server

  tasks:
    - name: Ensures docker is installed and configured on all hosts that may need it
      ansible.builtin.include_tasks: ./tasks/docker.yml

- name: Router configuration
  hosts: router

  tasks:
    - name: Configure wireguard for the router
      ansible.builtin.include_tasks: ./tasks/router_wireguard.yml

- name: Vulnbox wireguard configuration
  hosts: vulnbox

  tasks:
    - name: Configure wireguard for the vulnbox
      ansible.builtin.include_tasks: ./tasks/vulnbox_wireguard.yml

- name: Server configuration
  hosts: server

  tasks:
    - name: Configure wireguard for the server
      ansible.builtin.include_tasks: ./tasks/server_wireguard.yml

- name: Final router configuration and wireguard server start
  hosts: router

  tasks:
    - name: With all the wireguard peers configured, we can now ultimate the router's configuration
      ansible.builtin.include_tasks: ./tasks/router_final.yml

- name: Enable and start wireguard
  hosts:
    - vulnbox
    - server

  tasks:
    - name: Start and enable wireguard
      ansible.builtin.include_tasks: ./tasks/wireguard_start.yml
