name: Ansible CI

on:
  push:
    branches: [main]
    paths:
      - "ansible/**"
  pull_request:
    branches: [main]
    paths:
      - "ansible/**"
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install ansible-lint

      - name: Ansible Lint
        run: ansible-lint --offline ansible
